// Package agentmd generates AGENTS.md scaffolding — the cross-tool
// agent-readable instruction convention released August 2025 (OpenAI / Google /
// Cursor / Factory).
//
// Motivation (v0.32.0):
//
//	Martin Fowler's Harness Engineering taxonomy (2026-04) categorises harness
//	components as Computational × Inferential × Guide × Sensor. yagura v0.31
//	had 8 sensors but 0 guides (feedback-heavy, feedforward-blind).
//
//	AGENTS.md is the canonical Inferential Guide: a ~100-line table-of-contents
//	injected into Claude Code / Codex / Cursor / Factory at session start. It
//	tells the agent which conventions apply BEFORE acting.
//
//	yagura already knows portfolio-grade facts about each project (Plan.md
//	sections, language, depends_on, harness G7.x rules, scanner state). The
//	missing piece was producing a ready-to-use AGENTS.md from those facts.
//
// Design (ADR-0001 zero-dep):
//   - Template assembly (stdlib text only, no external templating lib)
//   - Pure function: ProjectFacts → string
//   - Deterministic output (sorted sections, stable wording)
//   - Cross-tool: emit one file consumable by both Claude Code (which reads
//     AGENTS.md as fallback to CLAUDE.md) and OpenAI Codex (which prefers
//     AGENTS.md)
//
// Reference:
//
//	https://openai.com/index/harness-engineering/
//	https://martinfowler.com/articles/harness-engineering.html
//	https://agents.md/
package agentmd

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// ProjectFacts is the structured input from registry + plantracker + scanners.
//
// All fields optional; absent fields are simply omitted from the generated
// AGENTS.md (no placeholder filler).
type ProjectFacts struct {
	Slug         string
	DisplayName  string
	Repository   string // owner/repo
	Language     string // primary language tag
	Stage        string // alpha / beta / production
	LocalPath    string
	Tags         []string
	Description  string // from Plan.md 目的 section if present
	Scope        string // from Plan.md スコープ
	Phases       []string
	DoD          []string
	DependsOn    []string
	HasCI        bool
	HasTests     bool
	CIStatus     string // passing / failing / unknown
	OpenIssues   int
	OpenPRs      int
	VulnCritical int
	VulnHigh     int
	GeneratedAt  time.Time
	GeneratedBy  string // "yagura vX.Y.Z"

	// Optional: project-local harness rules (defaults to a sensible portfolio set
	// that yagura uses across the sovereign computing stack).
	HarnessRules []HarnessRule
}

// HarnessRule is one bullet in the "House rules" section.
type HarnessRule struct {
	Topic string // "Testing", "Security", "Style"
	Rule  string // "All new functions must have tests before merge."
}

// Default rules align with m's harness G0.* / G7.* / G16 invariants.
// These are emitted unless the caller supplies a non-empty HarnessRules slice.
func defaultHarnessRules() []HarnessRule {
	return []HarnessRule{
		{"Testing", "Add or update tests for every behavior change. CI must be green before merge (G0.7)."},
		{"Security", "Treat all dependencies as untrusted until SBOM + vuln scan is clean (G7.x)."},
		{"AI code", "AI-generated code must be reviewed by a human and ship with tests (G0.7)."},
		{"Determinism", "Avoid wall-clock dependencies in tests; use NowFn-style injection."},
		{"Reproducibility", "Builds must be byte-for-byte reproducible (CGO_ENABLED=0 + -trimpath + -buildvcs=false)."},
		{"Observability", "Emit structured logs; prefer OTel / Prometheus over ad-hoc print statements (G16)."},
		{"Permissions", "Sensor data (vuln, ci status, scorecard) is scanner-only — never inject via MCP."},
	}
}

// Generate returns the full AGENTS.md body as a string.
//
// Output is deterministic given the same inputs. Sections are emitted only
// when their underlying data is non-empty, keeping the file lean (Fowler:
// "give the agent a map, not a manual").
func Generate(p ProjectFacts) string {
	var sb strings.Builder
	writeHeader(&sb, p)
	writePurpose(&sb, p)
	writeQuickFacts(&sb, p)
	writeScope(&sb, p)
	writePhases(&sb, p)
	writeDoD(&sb, p)
	writeDependsOn(&sb, p)
	writeRules(&sb, p)
	writeSensors(&sb, p)
	writeFooter(&sb, p)
	return sb.String()
}

func writeHeader(sb *strings.Builder, p ProjectFacts) {
	title := p.DisplayName
	if title == "" {
		title = p.Slug
	}
	if title == "" {
		title = "Project"
	}
	fmt.Fprintf(sb, "# AGENTS.md — %s\n\n", title)
	sb.WriteString("> This file is auto-generated by yagura. It is the agent-readable map of\n")
	sb.WriteString("> this repository, designed for Claude Code, OpenAI Codex, Cursor, and other\n")
	sb.WriteString("> coding agents that follow the AGENTS.md convention.\n>\n")
	sb.WriteString("> If you are a human, skim the section titles and read what looks relevant.\n>\n")
	sb.WriteString("> If you are an agent, read top-to-bottom; sections are ordered by what you\n")
	sb.WriteString("> need to know first.\n\n")
}

func writePurpose(sb *strings.Builder, p ProjectFacts) {
	if p.Description == "" {
		return
	}
	sb.WriteString("## Purpose\n\n")
	sb.WriteString(strings.TrimSpace(p.Description))
	sb.WriteString("\n\n")
}

func writeQuickFacts(sb *strings.Builder, p ProjectFacts) {
	type kv struct{ k, v string }
	var rows []kv
	add := func(k, v string) {
		if v != "" {
			rows = append(rows, kv{k, v})
		}
	}
	add("Repository", p.Repository)
	add("Primary language", p.Language)
	add("Stage", p.Stage)
	add("Local path", p.LocalPath)
	add("CI status", p.CIStatus)
	if len(p.Tags) > 0 {
		add("Tags", strings.Join(p.Tags, ", "))
	}
	if len(rows) == 0 {
		return
	}
	sb.WriteString("## Quick facts\n\n")
	for _, r := range rows {
		fmt.Fprintf(sb, "- **%s:** %s\n", r.k, r.v)
	}
	sb.WriteString("\n")
}

func writeScope(sb *strings.Builder, p ProjectFacts) {
	if strings.TrimSpace(p.Scope) == "" {
		return
	}
	sb.WriteString("## Scope\n\n")
	sb.WriteString(strings.TrimSpace(p.Scope))
	sb.WriteString("\n\n")
}

func writePhases(sb *strings.Builder, p ProjectFacts) {
	if len(p.Phases) == 0 {
		return
	}
	sb.WriteString("## Phases\n\n")
	for _, ph := range p.Phases {
		fmt.Fprintf(sb, "- %s\n", strings.TrimSpace(ph))
	}
	sb.WriteString("\n")
}

func writeDoD(sb *strings.Builder, p ProjectFacts) {
	if len(p.DoD) == 0 {
		return
	}
	sb.WriteString("## Definition of Done\n\n")
	for _, d := range p.DoD {
		fmt.Fprintf(sb, "- %s\n", strings.TrimSpace(d))
	}
	sb.WriteString("\n")
}

func writeDependsOn(sb *strings.Builder, p ProjectFacts) {
	if len(p.DependsOn) == 0 {
		return
	}
	sb.WriteString("## Upstream dependencies\n\n")
	sb.WriteString("This project depends on the following sibling projects in the portfolio.\n")
	sb.WriteString("Changes to their public interfaces may require coordination.\n\n")
	deps := append([]string{}, p.DependsOn...)
	sort.Strings(deps)
	for _, d := range deps {
		fmt.Fprintf(sb, "- `%s`\n", d)
	}
	sb.WriteString("\n")
}

func writeRules(sb *strings.Builder, p ProjectFacts) {
	rules := p.HarnessRules
	if len(rules) == 0 {
		rules = defaultHarnessRules()
	}
	// Group by topic, preserve given order within a topic.
	sb.WriteString("## House rules (harness invariants)\n\n")
	sb.WriteString("These rules must hold for every change. Most are enforced by yagura's\n")
	sb.WriteString("sensors (`quality_check`, `ai_verify`, `test_audit`, `vulns`, etc.). If you\n")
	sb.WriteString("find yourself wanting to skip a rule, write down why in the PR description.\n\n")

	byTopic := map[string][]string{}
	var topicOrder []string
	for _, r := range rules {
		if _, seen := byTopic[r.Topic]; !seen {
			topicOrder = append(topicOrder, r.Topic)
		}
		byTopic[r.Topic] = append(byTopic[r.Topic], r.Rule)
	}
	for _, t := range topicOrder {
		fmt.Fprintf(sb, "### %s\n\n", t)
		for _, rule := range byTopic[t] {
			fmt.Fprintf(sb, "- %s\n", rule)
		}
		sb.WriteString("\n")
	}
}

func writeSensors(sb *strings.Builder, p ProjectFacts) {
	if p.VulnCritical == 0 && p.VulnHigh == 0 && p.OpenIssues == 0 && p.OpenPRs == 0 {
		return
	}
	sb.WriteString("## Current sensor state\n\n")
	sb.WriteString("Snapshot from the most recent yagura scan. If any value here surprises\n")
	sb.WriteString("you, run `yagura_alert_fix` for the actionable recommendation.\n\n")
	if p.VulnCritical > 0 {
		fmt.Fprintf(sb, "- **CRITICAL vulnerabilities:** %d (block release; see `yagura_vulns`)\n", p.VulnCritical)
	}
	if p.VulnHigh > 0 {
		fmt.Fprintf(sb, "- **High vulnerabilities:** %d (fix within 2 weeks; G7.8)\n", p.VulnHigh)
	}
	if p.OpenIssues > 0 {
		fmt.Fprintf(sb, "- **Open issues:** %d\n", p.OpenIssues)
	}
	if p.OpenPRs > 0 {
		fmt.Fprintf(sb, "- **Open PRs:** %d\n", p.OpenPRs)
	}
	sb.WriteString("\n")
}

func writeFooter(sb *strings.Builder, p ProjectFacts) {
	sb.WriteString("## Provenance\n\n")
	by := p.GeneratedBy
	if by == "" {
		by = "yagura"
	}
	when := p.GeneratedAt
	if when.IsZero() {
		when = time.Now().UTC()
	}
	fmt.Fprintf(sb, "Generated by %s at %s.\n", by, when.Format(time.RFC3339))
	sb.WriteString("\nThis file is regenerated whenever portfolio metadata changes. ")
	sb.WriteString("Edit `Plan.md` and re-run `yagura_agents_md` to update.\n")
}
