// Package aiverify は AI 生成コードの risk pattern を検出する。
//
// 動機 (v0.25.0):
//   m's harness G0.7 INVARIANT「AI出力検証義務」への直接対応。
//
//   2026 の deep research で集まった統計:
//     - Veracode (100+ LLMs, 80 tasks): 45% of AI-generated code ships OWASP Top-10
//     - Apiiro Fortune 50: 10x security findings, 322% privilege-escalation paths, 40% secrets exposure
//     - CodeRabbit: 1.7× issue multiplier for AI code
//     - Georgia Tech Vibe Security Radar: 74 CVEs traceable to AI tools (2026/03)
//     - METR RCT (2025/07): AI tooling slowed experienced devs by 19% (despite predicting 24% speedup)
//
//   yagura の他 quality_check (一般 lint), secretscan (secrets), gha_audit (CI 設定)
//   と相補的に、"AI-generated 高 risk 箇所" を特定する。
//
// 設計判断 (ADR-0001 ゼロ依存):
//   - regex base の pattern detector (stdlib のみ)
//   - language-agnostic (Go/TS/Py/Rust 等を同 rule で扱う)
//   - AI marker comment (e.g., "// AI generated") を検出、その近傍 (±10 lines) を
//     "AI-generated zone" と扱い severity を 2x multiplier (1.7-1.75x を切り上げ)
//   - 6 category × 4 risk level
//   - dedupe cache 統合可能 (CacheLike interface)
//
// "AI が書いたコードを AI で review してはいけない" (Medium 2026) の助言を尊重し、
// rule base の検出器を採用 (LLM call なし)。これは regex の限界もあるが false positive
// が予測可能で、agent loop で再現性ある audit ができる。
package aiverify

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"regexp"
	"sort"
	"strings"
	"sync"
)

// RiskLevel は finding の重大度。
type RiskLevel string

const (
	// RiskCritical は即時修正が必要な最高リスクの finding (CVSS 9.0+相当)。
	RiskCritical RiskLevel = "CRITICAL"
	// RiskHigh は優先修正が推奨される高リスクの finding。
	RiskHigh RiskLevel = "HIGH"
	// RiskMedium は計画的対応が推奨される中リスクの finding。
	RiskMedium RiskLevel = "MEDIUM"
	// RiskLow は任意対応の低リスクの finding。
	RiskLow RiskLevel = "LOW"
)

// Category は finding 分類。
type Category string

const (
	// CategoryAuth は JWT・パスワードハッシュ・セッション等の認証/認可パターン。
	CategoryAuth Category = "auth"
	// CategoryBilling は Stripe 連携・通貨計算・返金処理等の課金パターン。
	CategoryBilling Category = "billing"
	// CategoryData は SQL mutation・DELETE/DROP 等のデータ操作パターン。
	CategoryData Category = "data"
	// CategoryExternal はタイムアウト未設定の HTTP 呼出等の外部通信パターン。
	CategoryExternal Category = "external"
	// CategoryCrypto は弱乱数・DES/RC4 等の暗号化パターン。
	CategoryCrypto Category = "crypto"
	// CategorySecret はハードコードされた API キー等のシークレットパターン。
	CategorySecret Category = "secret"
	// CategoryAIMark は AI 生成マーカーコメントの検出(近傍行の severity 2x 対象)。
	CategoryAIMark Category = "ai-mark"
)

// Rule は単一検出ルール。
type Rule struct {
	ID       string
	Pattern  *regexp.Regexp
	Category Category
	Risk     RiskLevel
	Message  string
	// Languages = nil なら全言語適用。
	Languages []string
}

// Finding は 1 検出結果。
type Finding struct {
	File     string    `json:"file"`
	Line     int       `json:"line"`
	Column   int       `json:"column,omitempty"`
	RuleID   string    `json:"rule_id"`
	Category Category  `json:"category"`
	Risk     RiskLevel `json:"risk"`
	Message  string    `json:"message"`
	Context  string    `json:"context,omitempty"` // 該当行の trimmed snippet
	AIGen    bool      `json:"ai_gen,omitempty"`  // AI-generated zone 内か
}

// Result は全 scan の集計。
type Result struct {
	FilesScanned int             `json:"files_scanned"`
	TotalLines   int             `json:"total_lines"`
	AIGenLines   int             `json:"ai_gen_lines"`
	Findings     []Finding       `json:"findings"`
	RiskScore    int             `json:"risk_score"` // 0-100
	BySeverity   map[RiskLevel]int `json:"by_severity"`
	ByCategory   map[Category]int  `json:"by_category"`
	HasCritical  bool            `json:"has_critical"`
	// v0.26.0: AI marker を持つが対応 test がない files (testcoverage 統合時)
	AIGenWithoutTests []string `json:"ai_gen_without_tests,omitempty"`
	// dedupe cache 統計 (ScanFilesCached 使用時のみ非ゼロ)
	CacheHits   int `json:"cache_hits,omitempty"`
	CacheMisses int `json:"cache_misses,omitempty"`
}

// aiMarkerRe は AI 生成 marker を検出する。case-insensitive。
//
// 検出例:
//   // AI generated
//   # AI generated (reviewed)
//   // Generated by Claude
//   /* @ai-generated */
//   // Copilot suggestion
//   // GPT-4 generated
var aiMarkerRe = regexp.MustCompile(`(?i)(?:^|[^a-zA-Z0-9_])(ai[ -]?generated|generated by (?:claude|copilot|gpt|chatgpt|cursor)|gpt[\d.-]*\s*generated|@ai-generated|copilot[ -]?suggestion|chatgpt|llm[ -]?generated)`)

// aiZoneRadius は marker の前後何行を "AI-generated zone" とみなすか。
//
// AI が生成した関数は通常 5-30 行。±10 行を保守的に取る。
const aiZoneRadius = 10

// compiledDefaultRules は正規表現を一度だけコンパイルして再利用する。
// 以前は DefaultRules() 呼び出し毎に 20+ 個の regexp.MustCompile が走り、
// scan するファイルごとに同一パターンを再コンパイルしていた。
var compiledDefaultRules = sync.OnceValue(buildDefaultRules)

// DefaultRules は yagura が出荷するデフォルト rule set。
// 返り値は呼び出し毎に独立した slice(backing array は共有しない)。
func DefaultRules() []Rule {
	rs := compiledDefaultRules()
	out := make([]Rule, len(rs))
	copy(out, rs)
	return out
}

func buildDefaultRules() []Rule {
	must := regexp.MustCompile
	return []Rule{
		// ─── Auth: CRITICAL ────────────────────────────────────
		{ID: "auth-md5-password",
			Pattern:  must(`(?i)md5\s*\([^)]*(password|passwd|pwd|secret)`),
			Category: CategoryAuth, Risk: RiskCritical,
			Message:  "MD5 used for password/secret hashing (use bcrypt/argon2 instead)"},
		{ID: "auth-sha1-password",
			Pattern:  must(`(?i)sha1\s*\([^)]*(password|passwd|pwd|secret)`),
			Category: CategoryAuth, Risk: RiskCritical,
			Message:  "SHA1 used for password/secret hashing (use bcrypt/argon2 instead)"},
		{ID: "auth-jwt-hs256-hardcoded",
			Pattern:  must(`(?i)jwt[\.\s][^(\n]*sign[^(\n]*\([^,]+,\s*['"][^'"]{4,}['"]`),
			Category: CategoryAuth, Risk: RiskCritical,
			Message:  "Hardcoded JWT signing secret"},
		{ID: "auth-jwt-hs256-algo",
			Pattern:  must(`(?i)["']HS(256|384|512)["']`),
			Category: CategoryAuth, Risk: RiskHigh,
			Message:  "HS256/384/512 symmetric JWT (prefer RS256/ES256 for distributed services)"},
		{ID: "auth-cookie-insecure",
			Pattern:  must(`(?i)secure\s*[:=]\s*false`),
			Category: CategoryAuth, Risk: RiskHigh,
			Message:  "Cookie/session with secure=false"},

		// ─── Billing: HIGH ─────────────────────────────────────
		{ID: "billing-float-currency",
			Pattern:  must(`(?i)(parseFloat|Number|float\.parse|float\()\s*\([^)]*(amount|price|cost|total|fee|charge)`),
			Category: CategoryBilling, Risk: RiskHigh,
			Message:  "Float used for currency (use Decimal/cents-as-int instead)"},
		{ID: "billing-stripe-uncaught",
			Pattern:  must(`(?i)stripe\.[\w]+\.(create|charge|capture|refund)\s*\(`),
			Category: CategoryBilling, Risk: RiskMedium,
			Message:  "Stripe API call — ensure idempotency_key + try/catch with retry"},

		// ─── Data: CRITICAL ────────────────────────────────────
		{ID: "data-delete-no-where",
			Pattern:  must(`(?i)DELETE\s+FROM\s+\w+\s*(;|"|'|$)`),
			Category: CategoryData, Risk: RiskCritical,
			Message:  "DELETE without WHERE clause (data wipe risk)"},
		{ID: "data-update-no-where",
			Pattern:  must(`(?i)UPDATE\s+\w+\s+SET\s+[^;]+?\s*(;|"|'|$)`),
			Category: CategoryData, Risk: RiskCritical,
			Message:  "UPDATE possibly without WHERE clause"},
		{ID: "data-drop-table",
			Pattern:  must(`(?i)DROP\s+(TABLE|DATABASE|SCHEMA)\b`),
			Category: CategoryData, Risk: RiskCritical,
			Message:  "DROP TABLE/DATABASE/SCHEMA (irreversible)"},
		{ID: "data-truncate",
			Pattern:  must(`(?i)TRUNCATE\s+TABLE`),
			Category: CategoryData, Risk: RiskCritical,
			Message:  "TRUNCATE TABLE (irreversible)"},

		// ─── External API: MEDIUM ──────────────────────────────
		{ID: "ext-fetch-no-timeout",
			Pattern:  must(`(?:^|[^.])fetch\s*\(\s*["'][^"']+["']\s*\)`),
			Category: CategoryExternal, Risk: RiskMedium,
			Message:  "fetch() without options object (no timeout/abort signal)"},
		{ID: "ext-http-get-go",
			Pattern:  must(`http\.Get\s*\(`),
			Category: CategoryExternal, Risk: RiskMedium,
			Message:  "http.Get without context — use http.NewRequestWithContext + client.Do for timeout",
			Languages: []string{"go"}},
		{ID: "ext-requests-no-timeout",
			Pattern:  must(`(?i)requests\.\w+\s*\([^)]*\)`),
			Category: CategoryExternal, Risk: RiskMedium,
			Message:  "requests call — ensure timeout= parameter is set",
			Languages: []string{"python", "py"}},

		// ─── Crypto: CRITICAL/HIGH ─────────────────────────────
		{ID: "crypto-math-rand-security",
			Pattern:  must(`(?i)(math/rand|Math\.random|math\.random|random\.random).*?(token|secret|key|password|nonce|salt|session)`),
			Category: CategoryCrypto, Risk: RiskCritical,
			Message:  "Non-crypto RNG used for security-sensitive value (use crypto/rand or secrets module)"},
		{ID: "crypto-weak-cipher-des",
			Pattern:  must(`(?i)(?:\b|New|new)(DES|RC4|3DES|TripleDES)\b`),
			Category: CategoryCrypto, Risk: RiskCritical,
			Message:  "Weak/broken cipher (DES/RC4/3DES) — use AES-256-GCM"},
		{ID: "crypto-ecb-mode",
			Pattern:  must(`(?i)["']\w*ECB\w*["']|\bMODE_ECB\b|CipherMode\.ECB`),
			Category: CategoryCrypto, Risk: RiskHigh,
			Message:  "ECB cipher mode (semantically insecure — use GCM/CBC with IV)"},

		// ─── Secret leak: CRITICAL ─────────────────────────────
		// secretscan と重複するが、AI generated 文脈で特に重視。
		{ID: "secret-stripe-live",
			Pattern:  must(`["'](sk|rk|pk)_live_[A-Za-z0-9]{24,}["']`),
			Category: CategorySecret, Risk: RiskCritical,
			Message:  "Stripe LIVE secret/restricted key hardcoded"},
		{ID: "secret-stripe-test",
			Pattern:  must(`["'](sk|rk|pk)_test_[A-Za-z0-9]{24,}["']`),
			Category: CategorySecret, Risk: RiskHigh,
			Message:  "Stripe TEST key hardcoded (rotate before public commit)"},
		{ID: "secret-github-pat",
			Pattern:  must(`["']ghp_[A-Za-z0-9]{36,}["']`),
			Category: CategorySecret, Risk: RiskCritical,
			Message:  "GitHub Personal Access Token hardcoded"},
		{ID: "secret-aws-akid",
			Pattern:  must(`["']AKIA[0-9A-Z]{16}["']`),
			Category: CategorySecret, Risk: RiskCritical,
			Message:  "AWS Access Key ID hardcoded"},
		{ID: "secret-openai-key",
			Pattern:  must(`["']sk-[A-Za-z0-9]{32,}["']`),
			Category: CategorySecret, Risk: RiskCritical,
			Message:  "OpenAI API key hardcoded"},
		{ID: "secret-anthropic-key",
			Pattern:  must(`["']sk-ant-[A-Za-z0-9_-]{32,}["']`),
			Category: CategorySecret, Risk: RiskCritical,
			Message:  "Anthropic API key hardcoded"},

		// ─── AI marker (informational, never blocking) ─────────
		{ID: "ai-marker-detected",
			Pattern:  aiMarkerRe,
			Category: CategoryAIMark, Risk: RiskLow,
			Message:  "AI-generated marker detected (validate per harness G0.7)"},
	}
}

// detectLanguage は path 拡張子から言語を推定する。
func detectLanguage(path string) string {
	switch {
	case strings.HasSuffix(path, ".go"):
		return "go"
	case strings.HasSuffix(path, ".ts"), strings.HasSuffix(path, ".tsx"):
		return "ts"
	case strings.HasSuffix(path, ".js"), strings.HasSuffix(path, ".jsx"):
		return "js"
	case strings.HasSuffix(path, ".py"):
		return "python"
	case strings.HasSuffix(path, ".rs"):
		return "rust"
	case strings.HasSuffix(path, ".java"):
		return "java"
	case strings.HasSuffix(path, ".c"), strings.HasSuffix(path, ".cpp"),
		strings.HasSuffix(path, ".cc"), strings.HasSuffix(path, ".h"),
		strings.HasSuffix(path, ".hpp"):
		return "c"
	default:
		return ""
	}
}

// ruleApplies は rule が language に対して有効か。
func ruleApplies(r Rule, language string) bool {
	if len(r.Languages) == 0 {
		return true
	}
	for _, l := range r.Languages {
		if l == language {
			return true
		}
	}
	return false
}

// findAIZones は content 内の AI marker 出現位置から ±aiZoneRadius 行を
// "AI-generated zone" として集合に追加する。
//
// 戻り値: line number (1-indexed) の set + total AI marker count。
func findAIZones(lines []string) (map[int]bool, int) {
	zones := map[int]bool{}
	markerCount := 0
	for i, line := range lines {
		if aiMarkerRe.MatchString(line) {
			markerCount++
			lineNum := i + 1
			start := lineNum - aiZoneRadius
			if start < 1 {
				start = 1
			}
			end := lineNum + aiZoneRadius
			if end > len(lines) {
				end = len(lines)
			}
			for n := start; n <= end; n++ {
				zones[n] = true
			}
		}
	}
	return zones, markerCount
}

// ScanText は単一 source の content を rule に対して走査する。
func ScanText(path, content string, rules []Rule) []Finding {
	lang := detectLanguage(path)
	lines := strings.Split(content, "\n")
	aiZones, _ := findAIZones(lines)

	var findings []Finding
	for i, line := range lines {
		lineNum := i + 1
		// trim for short context
		ctx := strings.TrimSpace(line)
		if len(ctx) > 120 {
			ctx = ctx[:117] + "..."
		}
		for _, r := range rules {
			if !ruleApplies(r, lang) {
				continue
			}
			loc := r.Pattern.FindStringIndex(line)
			if loc == nil {
				continue
			}
			findings = append(findings, Finding{
				File:     path,
				Line:     lineNum,
				Column:   loc[0] + 1,
				RuleID:   r.ID,
				Category: r.Category,
				Risk:     r.Risk,
				Message:  r.Message,
				Context:  ctx,
				AIGen:    aiZones[lineNum],
			})
		}
	}
	return findings
}

// CacheLike は dedupe.Cache に依存しないための minimal interface。
type CacheLike interface {
	Get(key string) ([]byte, bool)
	Set(key string, value []byte)
}

// Scan は複数 file 一括 scan。後方互換 shim。
func Scan(files map[string]string) Result {
	return scanImpl(files, DefaultRules(), nil)
}

// ScanCached は cache 統合版。同 content の重複 scan を skip。
func ScanCached(files map[string]string, cache CacheLike) Result {
	return scanImpl(files, DefaultRules(), cache)
}

// ScanWithRules はカスタム rule で scan する(v0.26+ で project 毎の rule 拡張用)。
func ScanWithRules(files map[string]string, rules []Rule) Result {
	return scanImpl(files, rules, nil)
}

func scanImpl(files map[string]string, rules []Rule, cache CacheLike) Result {
	res := Result{
		BySeverity: map[RiskLevel]int{},
		ByCategory: map[Category]int{},
	}
	for path, content := range files {
		res.FilesScanned++
		res.TotalLines += countLines(content)

		// AI marker 集計(zone とは別途、行数 metric として)
		lines := strings.Split(content, "\n")
		zones, markers := findAIZones(lines)
		if markers > 0 {
			// 各 marker から ±aiZoneRadius 行を AI gen と扱う
			res.AIGenLines += len(zones)
		}

		var fs []Finding
		if cache != nil {
			cacheKey := cacheKeyFor(path, content)
			if cached, ok := cache.Get(cacheKey); ok {
				if parsed, err := unmarshalFindings(cached); err == nil {
					fs = parsed
					res.CacheHits++
				}
			}
			if fs == nil {
				fs = ScanText(path, content, rules)
				res.CacheMisses++
				if data, err := json.Marshal(fs); err == nil {
					cache.Set(cacheKey, data)
				}
			}
		} else {
			fs = ScanText(path, content, rules)
		}

		for _, f := range fs {
			res.Findings = append(res.Findings, f)
			res.BySeverity[f.Risk]++
			res.ByCategory[f.Category]++
			if f.Risk == RiskCritical {
				res.HasCritical = true
			}
		}
	}

	// deterministic 順
	sortFindings(res.Findings)

	res.RiskScore = computeRiskScore(res.Findings)
	return res
}

// sortFindings は findings を決定論的な全順序で並べる。
//
// 入力は files map を range して作られる(= 走査順が非決定的)。sort.Slice は
// unstable なので、比較キーが全順序でないと「等しい」要素の相対順が走査順に依存し
// 出力が run ごとにブレる。File → Line → Column → RuleID まで tie-break して、
// 同一行に複数ルールがヒットしても順序を一意に確定させる。
func sortFindings(fs []Finding) {
	sort.Slice(fs, func(i, j int) bool {
		a, b := fs[i], fs[j]
		if a.File != b.File {
			return a.File < b.File
		}
		if a.Line != b.Line {
			return a.Line < b.Line
		}
		if a.Column != b.Column {
			return a.Column < b.Column
		}
		return a.RuleID < b.RuleID
	})
}

// computeRiskScore は findings から 0-100 の risk score を算出する。
//
// 重み付け (一般 SCA より AI generated を厳しめに):
//   CRITICAL × 25
//   HIGH     × 10
//   MEDIUM   × 3
//   LOW      × 1
//
// AI-generated zone 内の finding は **2x multiplier** を適用。
// CodeRabbit / Veracode が報告する 1.7-1.75× の issue rate を切り上げ。
//
// 最終 score は 100 で cap。
func computeRiskScore(findings []Finding) int {
	score := 0
	for _, f := range findings {
		var w int
		switch f.Risk {
		case RiskCritical:
			w = 25
		case RiskHigh:
			w = 10
		case RiskMedium:
			w = 3
		case RiskLow:
			w = 1
		}
		if f.AIGen {
			w *= 2
		}
		score += w
	}
	if score > 100 {
		score = 100
	}
	return score
}

// countLines は改行数 + 1(empty trailing line も 1 と数える簡素実装)。
func countLines(content string) int {
	if content == "" {
		return 0
	}
	return strings.Count(content, "\n") + 1
}

// cacheKeyFor は (path, content) から決定論的 cache key を生成する。
// quality_check と独立 namespace ("av:" prefix) を使用。
func cacheKeyFor(path, content string) string {
	h := sha256.Sum256([]byte(content))
	return "av:" + path + ":" + hex.EncodeToString(h[:])
}

func unmarshalFindings(data []byte) ([]Finding, error) {
	var fs []Finding
	err := json.Unmarshal(data, &fs)
	return fs, err
}

// Summary は人間可読 1 行サマリ。
func (r Result) Summary() string {
	var sb strings.Builder
	sb.WriteString("risk_score=")
	sb.WriteString(intToStr(r.RiskScore))
	sb.WriteString(" findings=")
	sb.WriteString(intToStr(len(r.Findings)))
	if c := r.BySeverity[RiskCritical]; c > 0 {
		sb.WriteString(" CRIT=")
		sb.WriteString(intToStr(c))
	}
	if h := r.BySeverity[RiskHigh]; h > 0 {
		sb.WriteString(" HIGH=")
		sb.WriteString(intToStr(h))
	}
	if r.AIGenLines > 0 {
		sb.WriteString(" ai_lines=")
		sb.WriteString(intToStr(r.AIGenLines))
	}
	return sb.String()
}

func intToStr(n int) string {
	if n == 0 {
		return "0"
	}
	var sb strings.Builder
	if n < 0 {
		sb.WriteByte('-')
		n = -n
	}
	digits := []byte{}
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	sb.Write(digits)
	return sb.String()
}

// TestAuditor は testcoverage.Audit 結果の minimal interface(循環 import 回避)。
type TestAuditor interface {
	HasTestFor(path string) bool
}

// AnnotateUntested は scan 結果に test 未対応の AI 生成 file を flag する。
//
// usage:
//
//	res := aiverify.Scan(files)
//	tcRes := testcoverage.Audit(files)
//	res = aiverify.AnnotateUntested(res, files, func(p string) bool {
//	    // testcoverage の HasTest を query
//	    ...
//	})
//
// 副次効果: risk_score が AIGenWithoutTests 件数 × 5 で増加(cap 100)。
func AnnotateUntested(res Result, files map[string]string, hasTest func(path string) bool) Result {
	if hasTest == nil {
		return res
	}
	// AI marker を含む各 file をチェック
	var untested []string
	for path, content := range files {
		lines := strings.Split(content, "\n")
		_, markers := findAIZones(lines)
		if markers == 0 {
			continue // AI marker なし、対象外
		}
		if !hasTest(path) {
			untested = append(untested, path)
		}
	}
	sort.Strings(untested)
	res.AIGenWithoutTests = untested

	// risk_score をさらに加算
	bonus := len(untested) * 5
	res.RiskScore += bonus
	if res.RiskScore > 100 {
		res.RiskScore = 100
	}
	return res
}
