package aiverify

import (
	"fmt"
	"regexp"
	"strings"
	"testing"
)

// ─── AI marker 検出 ───────────────────────────────

func TestAIMarker_Detected(t *testing.T) {
	cases := []string{
		"// AI generated",
		"# AI generated (reviewed)",
		"// Generated by Claude",
		"# Generated by Copilot",
		"/* @ai-generated */",
		"// Copilot suggestion",
		"# ChatGPT output",
		"// GPT-4 generated",
	}
	for _, in := range cases {
		if !aiMarkerRe.MatchString(in) {
			t.Errorf("should detect AI marker: %q", in)
		}
	}
}

func TestAIMarker_NotDetected(t *testing.T) {
	cases := []string{
		"// regular comment",
		"# python comment",
		"// generated config file", // "generated" alone shouldn't match
	}
	for _, in := range cases {
		if aiMarkerRe.MatchString(in) {
			t.Errorf("should NOT detect AI marker: %q", in)
		}
	}
}

// ─── AI zone (±10 lines) ─────────────────────────

func TestFindAIZones_MarkerExpandsZone(t *testing.T) {
	lines := []string{
		"line 1",
		"line 2",
		"line 3",
		"// AI generated", // line 4
		"line 5",
		"line 6",
	}
	zones, count := findAIZones(lines)
	if count != 1 {
		t.Errorf("marker count: got %d, want 1", count)
	}
	// ±10 範囲なので全 6 行が zone
	for i := 1; i <= 6; i++ {
		if !zones[i] {
			t.Errorf("line %d should be in AI zone", i)
		}
	}
}

func TestFindAIZones_NoMarker(t *testing.T) {
	lines := []string{"foo", "bar", "baz"}
	zones, count := findAIZones(lines)
	if count != 0 {
		t.Errorf("count: got %d, want 0", count)
	}
	if len(zones) != 0 {
		t.Errorf("zones should be empty")
	}
}

// ─── Auth rules ───────────────────────────────────

func TestRule_MD5Password(t *testing.T) {
	src := `// AI generated
hash := md5(password)
`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "auth-md5-password") {
		t.Errorf("auth-md5-password rule should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_HardcodedJWTSecret(t *testing.T) {
	src := `const tok = jwt.sign(payload, "supersecret123")`
	fs := ScanText("x.ts", src, DefaultRules())
	if !hasRule(fs, "auth-jwt-hs256-hardcoded") {
		t.Errorf("auth-jwt-hs256-hardcoded should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_CookieInsecure(t *testing.T) {
	src := `cookie.secure = false`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "auth-cookie-insecure") {
		t.Errorf("auth-cookie-insecure should fire")
	}
}

// ─── Billing rules ────────────────────────────────

func TestRule_FloatCurrency(t *testing.T) {
	src := `const total = parseFloat(amount)`
	fs := ScanText("x.js", src, DefaultRules())
	if !hasRule(fs, "billing-float-currency") {
		t.Errorf("billing-float-currency should fire")
	}
}

func TestRule_StripeCall(t *testing.T) {
	src := `stripe.charges.create({ amount: 1000 })`
	fs := ScanText("x.js", src, DefaultRules())
	if !hasRule(fs, "billing-stripe-uncaught") {
		t.Errorf("billing-stripe-uncaught should fire")
	}
}

// ─── Data rules ───────────────────────────────────

func TestRule_DeleteNoWhere(t *testing.T) {
	src := `db.exec("DELETE FROM users;")`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "data-delete-no-where") {
		t.Errorf("data-delete-no-where should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_DropTable(t *testing.T) {
	src := `db.exec("DROP TABLE users")`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "data-drop-table") {
		t.Errorf("data-drop-table should fire")
	}
}

// ─── Crypto rules ─────────────────────────────────

func TestRule_MathRandSecurity(t *testing.T) {
	src := `token := math.Random() // for session token`
	fs := ScanText("x.js", src, DefaultRules())
	if !hasRule(fs, "crypto-math-rand-security") {
		t.Errorf("crypto-math-rand-security should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_WeakCipherDES(t *testing.T) {
	src := `cipher := NewDES(key)`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "crypto-weak-cipher-des") {
		t.Errorf("crypto-weak-cipher-des should fire")
	}
}

// ─── Secret rules ─────────────────────────────────

func TestRule_StripeLiveKey(t *testing.T) {
	// Split across literals so push-protection scanners don't flag test fixtures.
	src := fmt.Sprintf(`const key = "%s"`, "sk_"+"live_AbCdEfGhIjKlMnOpQrStUvWxYz12")
	fs := ScanText("x.js", src, DefaultRules())
	if !hasRule(fs, "secret-stripe-live") {
		t.Errorf("secret-stripe-live should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_GitHubPAT(t *testing.T) {
	src := `token = "ghp_AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"`
	fs := ScanText("x.py", src, DefaultRules())
	if !hasRule(fs, "secret-github-pat") {
		t.Errorf("secret-github-pat should fire; got: %v", findingIDs(fs))
	}
}

func TestRule_AWSAKID(t *testing.T) {
	src := `AWS_KEY = "AKIAIOSFODNN7EXAMPLE"`
	fs := ScanText("x.py", src, DefaultRules())
	if !hasRule(fs, "secret-aws-akid") {
		t.Errorf("secret-aws-akid should fire")
	}
}

func TestRule_AnthropicKey(t *testing.T) {
	src := `key = "sk-ant-api03-AbCdEfGhIjKlMnOpQrStUvWxYz0123456789"`
	fs := ScanText("x.py", src, DefaultRules())
	if !hasRule(fs, "secret-anthropic-key") {
		t.Errorf("secret-anthropic-key should fire")
	}
}

// ─── External API ────────────────────────────────

func TestRule_FetchNoTimeout(t *testing.T) {
	src := `const r = fetch("https://api.example.com")`
	fs := ScanText("x.ts", src, DefaultRules())
	if !hasRule(fs, "ext-fetch-no-timeout") {
		t.Errorf("ext-fetch-no-timeout should fire")
	}
}

func TestRule_HttpGetGo(t *testing.T) {
	src := `resp, err := http.Get(url)`
	fs := ScanText("x.go", src, DefaultRules())
	if !hasRule(fs, "ext-http-get-go") {
		t.Errorf("ext-http-get-go should fire (Go context)")
	}
}

func TestRule_HttpGetNotInPython(t *testing.T) {
	// "http.Get" は Go 専用 rule
	src := `resp = http.Get(url)`
	fs := ScanText("x.py", src, DefaultRules())
	if hasRule(fs, "ext-http-get-go") {
		t.Errorf("ext-http-get-go should NOT fire in python file")
	}
}

// ─── AI multiplier ────────────────────────────────

func TestRiskScore_AIZoneMultiplier(t *testing.T) {
	// 同じ CRITICAL violation を、AI zone 内と外で比較
	srcOutsideAI := `db.exec("DROP TABLE users")`
	srcInsideAI := `// AI generated
db.exec("DROP TABLE users")
`
	r1 := Scan(map[string]string{"x.go": srcOutsideAI})
	r2 := Scan(map[string]string{"x.go": srcInsideAI})

	if r2.RiskScore <= r1.RiskScore {
		t.Errorf("AI zone should double risk: outside=%d inside=%d", r1.RiskScore, r2.RiskScore)
	}
	// CRITICAL × 25 = 25, AI で × 2 = 50, さらに ai-marker LOW×2=2 で計 52
	if r2.RiskScore != 50 && r2.RiskScore != 51 && r2.RiskScore != 52 {
		t.Errorf("AI zone score: got %d, expected ~50-52", r2.RiskScore)
	}
}

// ─── Risk score 集計 ──────────────────────────────

func TestRiskScore_CapsAt100(t *testing.T) {
	// 大量の CRITICAL を生成して 100 で cap されるか
	var sb strings.Builder
	for i := 0; i < 20; i++ {
		sb.WriteString(`db.exec("DROP TABLE x")
`)
	}
	r := Scan(map[string]string{"x.go": sb.String()})
	if r.RiskScore != 100 {
		t.Errorf("should cap at 100, got %d", r.RiskScore)
	}
}

func TestRiskScore_ZeroWithoutFindings(t *testing.T) {
	r := Scan(map[string]string{"x.go": "package main\nfunc main() {}\n"})
	if r.RiskScore != 0 {
		t.Errorf("clean code should be 0, got %d", r.RiskScore)
	}
}

// ─── HasCritical ─────────────────────────────────

func TestResult_HasCritical(t *testing.T) {
	clean := Scan(map[string]string{"x.go": "func main() {}"})
	if clean.HasCritical {
		t.Error("clean code should not have critical")
	}
	bad := Scan(map[string]string{"x.go": `db.exec("DROP TABLE users")`})
	if !bad.HasCritical {
		t.Error("DROP TABLE should yield HasCritical=true")
	}
}

// ─── 集計 ────────────────────────────────────────

func TestResult_AggregatesBySeverityAndCategory(t *testing.T) {
	// Split across literals so push-protection scanners don't flag test fixtures.
	src := fmt.Sprintf("// AI generated\ndb.exec(\"DROP TABLE x\")\nkey := \"%s\"\ncookie.secure = false\n",
		"sk_"+"live_AAAAAAAAAAAAAAAAAAAAAAAA")
	r := Scan(map[string]string{"x.go": src})
	if r.BySeverity[RiskCritical] < 2 {
		t.Errorf("should have ≥2 CRITICAL; got %d", r.BySeverity[RiskCritical])
	}
	if r.BySeverity[RiskHigh] < 1 {
		t.Errorf("should have ≥1 HIGH; got %d", r.BySeverity[RiskHigh])
	}
	if r.ByCategory[CategoryData] < 1 {
		t.Errorf("should have data finding")
	}
	if r.ByCategory[CategorySecret] < 1 {
		t.Errorf("should have secret finding")
	}
}

// ─── Cache 統合 ─────────────────────────────────

type fakeCache struct {
	store  map[string][]byte
	hits   int
	misses int
}

func newFakeCache() *fakeCache { return &fakeCache{store: map[string][]byte{}} }
func (f *fakeCache) Get(k string) ([]byte, bool) {
	v, ok := f.store[k]
	if ok {
		f.hits++
		return v, true
	}
	f.misses++
	return nil, false
}
func (f *fakeCache) Set(k string, v []byte) { f.store[k] = v }

func TestScanCached_HitsOnRescan(t *testing.T) {
	cache := newFakeCache()
	files := map[string]string{"x.go": `db.exec("DROP TABLE users")`}

	r1 := ScanCached(files, cache)
	if r1.CacheMisses != 1 {
		t.Errorf("first scan: misses=%d, want 1", r1.CacheMisses)
	}
	r2 := ScanCached(files, cache)
	if r2.CacheHits != 1 {
		t.Errorf("rescan: hits=%d, want 1", r2.CacheHits)
	}
	// findings 同一
	if len(r1.Findings) != len(r2.Findings) {
		t.Errorf("findings should match: %d vs %d", len(r1.Findings), len(r2.Findings))
	}
}

// ─── Language-specific rule ──────────────────────

func TestDetectLanguage(t *testing.T) {
	cases := map[string]string{
		"a.go":   "go",
		"a.ts":   "ts",
		"a.tsx":  "ts",
		"a.js":   "js",
		"a.py":   "python",
		"a.rs":   "rust",
		"a.java": "java",
		"a.cpp":  "c",
		"a.md":   "",
	}
	for path, want := range cases {
		if got := detectLanguage(path); got != want {
			t.Errorf("detectLanguage(%s): got %q, want %q", path, got, want)
		}
	}
}

// ─── Summary ────────────────────────────────────

func TestResult_Summary(t *testing.T) {
	r := Scan(map[string]string{"x.go": `// AI generated
db.exec("DROP TABLE x")`})
	s := r.Summary()
	if !strings.Contains(s, "risk_score=") {
		t.Errorf("summary missing risk_score: %s", s)
	}
	if !strings.Contains(s, "CRIT=") {
		t.Errorf("summary missing CRIT: %s", s)
	}
}

// ─── helpers ───────────────────────────────────

func hasRule(fs []Finding, id string) bool {
	for _, f := range fs {
		if f.RuleID == id {
			return true
		}
	}
	return false
}

func findingIDs(fs []Finding) []string {
	out := make([]string, len(fs))
	for i, f := range fs {
		out[i] = f.RuleID
	}
	return out
}

// ─── AnnotateUntested (v0.26 testcoverage 統合) ──────

func TestAnnotateUntested_BumpsScoreForAIWithoutTest(t *testing.T) {
	files := map[string]string{
		"auth.go": "// AI generated\nfunc x() {}",
		"foo.go":  "// not ai\nfunc y() {}",
	}
	res := Scan(files)
	// auth.go は AI 生成、test なし(test map に何もない)
	res2 := AnnotateUntested(res, files, func(p string) bool { return false })
	// AI gen file 1 つで +5
	if res2.RiskScore < res.RiskScore+5 {
		t.Errorf("score should bump by 5: before=%d after=%d", res.RiskScore, res2.RiskScore)
	}
	if len(res2.AIGenWithoutTests) != 1 || res2.AIGenWithoutTests[0] != "auth.go" {
		t.Errorf("untested list: %v", res2.AIGenWithoutTests)
	}
}

func TestAnnotateUntested_SkipFilesWithTest(t *testing.T) {
	files := map[string]string{
		"auth.go": "// AI generated\nfunc x() {}",
	}
	res := Scan(files)
	res2 := AnnotateUntested(res, files, func(p string) bool { return true }) // 全 file test あり
	if len(res2.AIGenWithoutTests) != 0 {
		t.Errorf("with tests: should be empty, got %v", res2.AIGenWithoutTests)
	}
	if res2.RiskScore != res.RiskScore {
		t.Errorf("score should not change: %d vs %d", res.RiskScore, res2.RiskScore)
	}
}

func TestAnnotateUntested_NoAIMarkersNoEffect(t *testing.T) {
	files := map[string]string{
		"plain.go": "package x\nfunc x() {}",
	}
	res := Scan(files)
	res2 := AnnotateUntested(res, files, func(p string) bool { return false })
	if len(res2.AIGenWithoutTests) != 0 {
		t.Errorf("no AI markers: should be empty, got %v", res2.AIGenWithoutTests)
	}
}

func TestAnnotateUntested_NilHasTestNoop(t *testing.T) {
	files := map[string]string{"x.go": "// AI generated\nfunc x() {}"}
	res := Scan(files)
	res2 := AnnotateUntested(res, files, nil)
	if len(res2.AIGenWithoutTests) != 0 {
		t.Error("nil hasTest should yield no annotations")
	}
}

func TestAnnotateUntested_CapsAt100(t *testing.T) {
	// 20 AI-generated untested files → 20*5=100 bonus, but should cap
	files := map[string]string{}
	for i := 0; i < 25; i++ {
		files[fmt.Sprintf("f%d.go", i)] = "// AI generated\nfunc x() {}"
	}
	res := Scan(files)
	res2 := AnnotateUntested(res, files, func(p string) bool { return false })
	if res2.RiskScore != 100 {
		t.Errorf("should cap at 100, got %d", res2.RiskScore)
	}
}

// ─── Fuzz tests (v0.28) ───────────────────────────────────

// FuzzScan は任意の content を scan して panic しないことを確認。
//
// 期待: malformed input (binary, 巨大行, 特殊正規表現メタ文字, 未終端文字列)
// で ScanText / Scan / AnnotateUntested が panic / 無限ループしない。
// 不変量: risk_score は 0-100 範囲、findings の line ≥ 1。
func FuzzScan(f *testing.F) {
	seeds := []string{
		"",
		// Split across literals so push-protection scanners don't flag test fixtures.
		"// AI generated\\nconst x = \"sk_" + "live_abcdefghijklmnopqrstuvwx\"",
		`db.exec("DROP TABLE users")`,
		strings.Repeat("a", 10000),
		"\x00\x01\x02 binary",
		`md5(password)`,
		"// Generated by Claude\n// Generated by Copilot\n// AI generated\n",
		"\n\n\n\n",
		"[regex meta]{1,3}*?",
	}
	for _, s := range seeds {
		f.Add(s)
	}
	f.Fuzz(func(t *testing.T, content string) {
		// path にも fuzz は当たらないので固定
		res := Scan(map[string]string{"fuzz.go": content})
		// 不変量
		if res.RiskScore < 0 || res.RiskScore > 100 {
			t.Errorf("risk_score out of range: %d", res.RiskScore)
		}
		for _, f := range res.Findings {
			if f.Line < 1 {
				t.Errorf("finding line < 1: %d", f.Line)
			}
		}
		// Summary も panic しないこと
		_ = res.Summary()
	})
}

func TestScanWithRules_UsesCustomRules(t *testing.T) {
	custom := []Rule{
		{
			ID:       "CUSTOM-001",
			Pattern:  regexp.MustCompile(`(?i)DROP\s+TABLE\s+users`),
			Risk:     RiskHigh,
			Category: CategoryData,
		},
	}
	files := map[string]string{"q.go": "// DROP TABLE users\nfunc main() {}"}
	r := ScanWithRules(files, custom)
	if r.FilesScanned != 1 {
		t.Errorf("FilesScanned = %d, want 1", r.FilesScanned)
	}
}

// TestScan_DeterministicOrder_SamePositionCollision is the integration-level
// fence for the determinism invariant: Scan ranges the input files map (Go
// randomizes map iteration), so its public output must still be byte-stable
// across runs. Two rules matching the same token produce findings at the same
// File/Line/Column differing only by RuleID — the collision that exposed the
// non-total-order sort. Running many times catches any reintroduced
// map-order-dependent ordering (e.g. a future unsorted map-range).
func TestScan_DeterministicOrder_SamePositionCollision(t *testing.T) {
	rules := []Rule{
		{ID: "z-rule", Pattern: regexp.MustCompile(`SECRET`), Category: CategoryData, Risk: RiskHigh, Message: "z"},
		{ID: "a-rule", Pattern: regexp.MustCompile(`SECRET`), Category: CategoryData, Risk: RiskHigh, Message: "a"},
	}
	files := map[string]string{}
	for i := 0; i < 20; i++ {
		files[fmt.Sprintf("f%02d.go", i)] = "x := SECRET\n"
	}
	sig := func(r Result) string {
		var sb strings.Builder
		for _, f := range r.Findings {
			fmt.Fprintf(&sb, "%s:%d:%d:%s\n", f.File, f.Line, f.Column, f.RuleID)
		}
		return sb.String()
	}
	want := sig(ScanWithRules(files, rules))
	if want == "" {
		t.Fatal("expected findings from colliding rules, got none")
	}
	for run := 0; run < 40; run++ {
		if got := sig(ScanWithRules(files, rules)); got != want {
			t.Fatalf("run %d: non-deterministic Scan order over map input\nwant:\n%s\ngot:\n%s", run, want, got)
		}
	}
}
