// mcpdoc_test.go: docs/MCP_TOOLS.md is generated by `make docs-mcp` but nothing
// forces it to stay current — it silently sat at 62 tools while 71 were
// registered. This guard ties the committed reference to the live registry on
// two axes: the "**N tools**" headline count AND the presence of every
// registered tool name as a "### `name`" entry. A added/renamed tool without a
// regen fails CI. (Same drift-killing guard as skilldoc_test / readmedoc_test,
// but name-complete.)
package main

import (
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/shizukutanaka/yagura/internal/mcp"
	"github.com/shizukutanaka/yagura/internal/registry"
)

func TestMCPDoc_ReferenceMatchesRegistered(t *testing.T) {
	reg, err := registry.New(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	s := mcp.New("", nil)
	mcp.RegisterDefaultTools(s, mcp.Deps{Registry: reg, Now: func() time.Time { return time.Unix(0, 0) }})
	names := s.ToolNames()

	const path = "../../docs/MCP_TOOLS.md"
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	doc := string(b)

	// 1) headline count
	m := regexp.MustCompile(`\*\*(\d+) tools\*\*`).FindStringSubmatch(doc)
	if m == nil {
		t.Fatalf("%s: could not find a \"**N tools**\" headline to verify", path)
	}
	if stated, _ := strconv.Atoi(m[1]); stated != len(names) {
		t.Errorf("%s headline says %d tools but %d are registered — run `make docs-mcp`",
			path, stated, len(names))
	}

	// 2) every registered tool must have an entry (catches add/rename without regen)
	var missing []string
	for _, n := range names {
		if !strings.Contains(doc, "### `"+n+"`") {
			missing = append(missing, n)
		}
	}
	if len(missing) > 0 {
		t.Errorf("%s is missing entries for %d tool(s): %v — run `make docs-mcp`",
			path, len(missing), missing)
	}
}
